### ISSUE TITLE
Cannot start on Fedora 32

### ISSUE THREAD

**Issue by fchiacchiaretta** [etlegacy/etlegacy#1443]
Hello,
I just tried to start ET Legacy 2.76 64 bit on Fedora 32 and it fails with this error

```
Sys_LoadGameDll -> FS_CL_ExtractFromPakFile(/home/myuser/.etlegacy, legacy, ui.mp.x86_64.so)
Sys_LoadDll(/home/myuser/.etlegacy/legacy/ui.mp.x86_64.so)... failed: "Failed loading /home/myuser/.etlegacy/legacy/ui.mp.x86_64.so: /home/myuser/.etlegacy/legacy/ui.mp.x86_64.so: undefined symbol: __acosf_finite"
Sys_LoadDll(./legacy/ui.mp.x86_64.so)... failed: "Failed loading ./legacy/ui.mp.x86_64.so: ./legacy/ui.mp.x86_64.so: cannot open shared object file: No such file or directory"
Sys_LoadDll(legacy/ui) failed to load library
```

File `ui.mp.x86_64.so` exists in `/home/myuser/.etlegacy/legacy/`, if I try to copy it in `PREFIX/etlegacy-v2.76-x86_64/legacy` I get the same undefined symbol error on `Sys_LoadDll(./legacy/ui.mp.x86_64.so)` instead of `No such file or directory`.

I also tried to reinstall with installer, but the same issue appears.
It was working properly on Fedora 31 before upgrading to 32.

Best,
Federico Chiacchiaretta

**Comment by rmarquis** [comment]
A similar issue happened in the past but on renderer module, see #476.

There might be some linking needed with `libm`, but I'm not sure what made it suddenly fail with the new Fedora release. Arch Linux users reported the same issue [here](https://aur.archlinux.org/packages/etlegacy) and [there](https://aur.archlinux.org/packages/etlegacy-git) too.

**Comment by rmarquis** [comment]
This issue was due to the new GLibc 2.31, relased on 2020-02-01 and gradually introduced in newer Linux distribution.

@fchiacchiaretta This is now fixed in master code, but you'll want to self-compile to be able to play on Fedora 32. See README.

**Comment by ghost** [comment]
I am using Fedora 33 x64.
I managed to compile the game and run it, but when I connect to a server, the game crashes and gives me the same error message so the problem was not resolved.

**Comment by isRyven** [comment]
First of all, the problem was related to UI module, which is usually distributed by the server in case the right version does not present on the client, so it doesn't really matter whether you are using self compiled executable or not. Secondly, the issue __is__ fixed in master, but in case you will attempt to connect to `2.76` server and be forced to download the `2.76` paks, you will run into the issue. There is nothing to do about it, you can instead compile or use 32 bit executable, since the problem only affects 64bit binaries.
